#!/bin/bash

# In order to cross-compile node for Android using NDK, run:
#   source android-configure <path_to_ndk> [arch]
#
# By running android-configure with source, will allow environment variables to
# be persistent in current session. This is useful for installing native node
# modules with npm. Also, don't forget to set the arch in npm config using
# 'npm config set arch=<arch>'


if [ -z "$2" ]; then
    ARCH=arm
else
    ARCH="$2"
fi

CC_VER="4.9"
case $ARCH in
    arm)
        DEST_CPU="$ARCH"
        SUFFIX="$ARCH-linux-androideabi"
        TOOLCHAIN_NAME="$SUFFIX"
        ;;
    arm64)
        DEST_CPU="$ARCH"
        SUFFIX="aarch64-linux-android-4.9"
        TOOLCHAIN_NAME="$SUFFIX"
        ;;
    armv7l)
        DEST_CPU="$ARCH"
        SUFFIX="$ARCH-linux-androideabi"
        TOOLCHAIN_NAME="$SUFFIX"
        ;;
    x86)
        DEST_CPU="ia32"
        SUFFIX="i686-linux-android"
        TOOLCHAIN_NAME="$ARCH"
        ;;
    x86_64)
        DEST_CPU="ia32"
        SUFFIX="$ARCH-linux-android"
        TOOLCHAIN_NAME="$ARCH"
        ;;
    *)
        echo "Unsupported architecture provided: $ARCH"
        exit 1
        ;;
esac

NDK_PATH=$1
function make_toolchain {
#    $NDK_PATH/build/tools/make-standalone-toolchain.sh \
#         --toolchain=$TOOLCHAIN_NAME-$CC_VER \
#        --arch=$ARCH \
#        --install-dir=$TOOLCHAIN \
#        --platform=android-21
     $NDK_PATH/build/tools/make_standalone_toolchain.py \
        --arch $ARCH \
        --install-dir $TOOLCHAIN \
        --api 24 \
        --stl libc++
}

export TOOLCHAIN=$PWD/android-toolchain
if [ -d "$TOOLCHAIN" ]; then
    read -r -p "NDK toolchain already exists. Replace it?  [y/N]" response
    case "$response" in
        [Yy])
            rm -rf "$TOOLCHAIN"
            make_toolchain
    esac
else
    make_toolchain
fi

export PATH=$TOOLCHAIN/bin:$PATH

# export AR=$TOOLCHAIN/bin/$SUFFIX-ar
# export CC=$TOOLCHAIN/bin/$SUFFIX-gcc
# export CXX=$TOOLCHAIN/bin/$SUFFIX-g++
# export LINK=$TOOLCHAIN/bin/$SUFFIX-g++

export AR_target="$TOOLCHAIN/bin/llvm-ar"
export CC_target="$TOOLCHAIN/bin/clang"
export CXX_target="$TOOLCHAIN/bin/clang++"
export LINK_target="$TOOLCHAIN/bin/clang++"
export READELF_target="$TOOLCHAIN/bin/$SUFFIX-readelf"
export NM_target="$TOOLCHAIN/bin/$SUFFIX-nm"

export AR_host=$(which ar)
export CC_host=$(which gcc)
export CXX_host=$(which g++)
export LINK_host=$(which g++)
export READELF_host=$(which readelf)
export NM_host=$(which nm)

GYP_DEFINES="target_arch=$ARCH"
GYP_DEFINES+=" v8_target_arch=$ARCH"
GYP_DEFINES+=" android_target_arch=$ARCH"
GYP_DEFINES+=" host_os=linux host_arch=x86 OS=android"

# GYP_DEFINES+=" host_os=linux host_arch=x64 OS=android is_component_build=true"
# GYP_DEFINES+=" library=shared component=shared_library"
export GYP_DEFINES


if [ -f "configure" ]; then
    ./configure \
        --cross-compiling \
        --dest-cpu=$DEST_CPU \
        --dest-os=android \
        --openssl-no-asm \
        --with-intl=full-icu \
        --download=all \
        --ninja \
        --enable-d8 \
        --shared
fi
